import '/assets/styles/About.css'; // Assuming you have a CSS file for styling

const About = () => {
    return <main>
        <h1 className='anglerfish'>About Anglerfish</h1>
        <p className='first-paragraph'>Life in the deep sea is not one for the faint of heart, there are a multitude of different fishes there that have special adaptations to improve their ability to feed and to mate. The deep sea Annglerfish may not regularly encounter a suitable prey, so they have large mouths and stomachs along with long, pointy teeth in order to facilitate a capturing and swallowing of anythinng they find. Anglerfish are a bony fish named for their characteristic mode of predation, in which a fleshy growth from the fish's head (the esca or illicium) acts as a lure. The deep sea Anglerfish's lure is filled with bacteria that make their own light. Whilst using a muscular skin flap, these fish can either hide or reveal their lighted lure. Through pulsing the light and moving it back an forth, they can succesfully attract pelagic crustaceans, fishes, and other prey.</p> 
        <p className='paragraph'>Anglerfish are also notable for extreme sexual dimorphism seen in the suborder Ceratioidei, and sexual parasitism of males to females. The female Anglerfishes lure is also used to attarct a mate  Females are the large, ambush predators: Females have the lighted lures. Males are very small in size, usuall only reaching about an inch in length and are not predatory what-so-ever. Once an Anglerfish hatches. they spen all of their energy serching for mates biting on larger females, and fertilizing their eggs. in many cases the male becomes partasitic never releasing from the female anglerfish, but in the deep sea Anglerfish, thats not the case. After only a short union, the male releases and seeks out another mate. Even though these fish do create a tight bond during the mating process, reproduction occurs via external fertilization. The female then release her eggs into the deep water colkumn, and the male immediately releases his sperm, which locate and fertilize the eggs.</p>
        <p className='paragraph'>On this fanpage our main focus is one small Anglerfish whos story of hope and determanation has swept the globe. On January 26, 2025, what is to believed the first ever sighting of the black seadevil deep-sea anglerfish was observed off the cost of Tenerife, in the Canary islands. Acorrding to an article from national geographic black seadevils hail  from a genus which translates as "black sea monster," which is a fitting name given their gaping jaws, sharp fangs, and bioluminescebt lures attached to their foreheads that they use to beguile their prey. The black sea devil may sound terrifying, but only if you're the size of our fishy friends Nemo and Dory, as these fish are onnly about six inches long. according to Kory Evans, a fish biologist ay Rice University, when the video of our black sea devil friend came to light they "Honestly didnt believ what they were seeing" and "Thought it was A.I." Bruce Robison, a senior scientist at the Monterey Bay Aquarium Reaserach Intstitute said "It's a really rare event to see a Deep-Sea critter like that close to the surface." Robinson, whop is said to know better than most on this subject, is the one who recorded the only other footage of a living black seadevil, a sxpeciemen that is normally spotted atb a depth of 1900 fett by the remotely operated vehicle Doc Ricketts in Monterey Bay in 2014.</p>
        <p className='paragraph'>The big questionstill remains, why di the black seadevil come to the oceans surface? Well, accoridng to Kory Evans, he was severely impressed that the anglerfish was not only intact but actually swimming - which is severely unexpected for a creature adapted to extreme pressures of the deep sea. "Their whole deal is not moving" said evans in a national geographic article, "They are ambushg predators, which means they sit there, bobbing around. So seeing this one doing something active is kind of shocking." Mr. Evans then continues to add "These fish look ferocious and fearsome, but they're mostly soft and squishy." While we may never really know for sure why the black seadevil made its way to the surcafe, there certainly very few likely scenarios for this once in a lifetime incident.</p>
    </main>;
  };
  export default About;